---
repos:
  - repo: local
    hooks:
      - id: check-nix-fmt
        name: 'Check nix fmt'
        entry: 'nixpkgs-fmt'
        files: \.nix$
        language: system
        stages:
          - commit
          - push
      - id: lint-nix-fmt
        name: 'Lint nix'
        entry: 'nix-linter'
        files: \.nix$
        language: system
        stages:
          - commit
          - push

  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.2.3
    hooks:
      -
        id: trailing-whitespace
        stages:
          - commit
          - push
      -
        id: check-merge-conflict
        stages:
          - commit
          - push
      -
        id: fix-encoding-pragma
        stages:
          - commit
          - push
      -
        id: check-symlinks
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.11.0
    hooks:
      -
        id: gitlint
        stages:
          - commit-msg
